# Set LabManger configuration file fields you wish to override from the default file stored in
# labmanager-common/lmcommon/configuration/config/labmanager.yaml.default

core:
  import_demo_on_first_login: false

flask:
  DEBUG: false
  TESTING: false

auth:
  identity_manager: anonymous

git:
  backend: filesystem-shim
  default_remote: repo.gtm-dev.cloud
  lfs_enabled: true
  remotes:
    repo.gtm-dev.cloud:
      remote_type: gitlab
      hub_api: https://gtm-dev.cloud/api/v1/
      object_service: api.gtm-dev.cloud/object-v1
  working_directory: /mnt/gigantum

environment:
  iframe:
    enabled: true
    allowed_origin: gtm-dev.cloud

# LabBook Container Configuration
container:
  context: hub
  build_timeout: 900

  # If null, no limit
  # To set enter string with a units identification char (e.g. 100000b, 1000k, 128m, 1g)
  memory: 4g
  # If null, no limit
  # To set enter a float for the CPU allocation desired. e.g. 4 CPUs available, 1.5 limits container to 1.5 CPUs
  cpu: 1

# Dispatcher and permitted number of workers -
# NOTE! Only the default queue is burstable
dispatcher:
  gigantum_default_queue: 6
  gigantum_build_queue: 1
  gigantum_publish_queue: 2